### ISSUE TITLE
扫描结果Banli is nei 或者wai ，结果资产总数都是6个。是因为没有这个类型的资产所产生的提示吗？

### ISSUE THREAD

**Issue by yangshifan-git** [0e0w/Chestnut#3]
直接扫描的oa资产
![image](https://user-images.githubusercontent.com/59814204/167235017-e55a6a85-d008-4b41-bc6d-8f159072517d.png)

**Comment by 0e0w** [comment]
把urls.txt里面的内容替换成你自己的。然后扫描试试？
